In [14]:
#Import Libraries
import pandas as pd
from pandas import read_csv
from numpy  import set_printoptions
from sklearn import preprocessing
from sklearn.impute import SimpleImputer

1. Load the Data Set

In [15]:

file_path = 'BADR Exel Sheet.csv'
BaDr_Data = pd.read_csv(file_path)
BaDr_Data.head()

,ProjectID,ProjectName,ProjectType,ProjectSize,ProjectComplexity,StartDate,EndDate,NumWorkers,HourlyRate,OvertimeRate,...,FringeBenefits,IndirectCosts,EquipmentCost,MaterialCost,ContingencyCost,WeatherImpact,WorkingHoursPerDay,WorkingDaysPerWeek,Holidays,LaborCost
0,210,Project 210,Industrial,8270,Simple,01-04-07,10-02-07,48,12.50,59.70,...,7.34,1232.33,17992.64,34044.60,3832.29,Low,7,5,6,1555000
1,211,Project 211,Industrial,7949,Complex,01-06-07,07-07-09,125,17.00,16.01,...,11.48,2164.92,14177.79,15579.75,2168.58,Low,9,5,20,4765000
2,212,Project 212,Residential,3734,Complex,01-06-07,12-11-08,114,16.06,17.04,...,NaN,1682.10,5975.77,47955.42,4862.53,Low,7,6,15,3725000
3,213,Project 213,Residential,8513,Complex,03-14-07,08-06-09,125,17.65,18.80,...,17.50,1693.46,10865.91,17289.44,4021.45,Low,7,6,19,4580000
4,214,Project 214,Residential,4843,Moderate,03-19-07,06-13-08,83,13.69,7.46,...,18.90,3909.09,9898.11,32817.76,3083.34,Low,7,6,10,2460000

In [16]:
BaDr_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 482 entries, 0 to 481
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ProjectID           482 non-null    int64
 1   ProjectName         482 non-null    object
 2   ProjectType         482 non-null    object
 3   ProjectSize         482 non-null    int64
 4   ProjectComplexity   482 non-null    object
 5   StartDate           482 non-null    object
 6   EndDate             482 non-null    object
 7   NumWorkers          482 non-null    int64
 8   HourlyRate          482 non-null    float64
 9   OvertimeRate        478 non-null    float64
 10  ProductivityRate    476 non-null    float64
 11  MarketWageRate      478 non-null    float64
 12  InflationRate       482 non-null    float64
 13  MinWage             482 non-null    float64
 14  LaborDemand         482 non-null    object
 15  FringeBenefits      476 non-null    float64
 16  IndirectCosts       482 non-null    float64
 17  EquipmentCost       482 non-null    float64
 18  MaterialCost        482 non-null    float64
 19  ContingencyCost     478 non-null    float64
 20  WeatherImpact       482 non-null    object
 21  WorkingHoursPerDay  482 non-null    int64
 22  WorkingDaysPerWeek  482 non-null    int64
 23  Holidays            482 non-null    int64
 24  LaborCost           482 non-null    int64
dtypes: float64(11), int64(7), object(7)
memory usage: 94.3+ KB

In [17]:
BaDr_Data.describe()

,ProjectID,ProjectSize,NumWorkers,HourlyRate,OvertimeRate,ProductivityRate,MarketWageRate,InflationRate,MinWage,FringeBenefits,IndirectCosts,EquipmentCost,MaterialCost,ContingencyCost,WorkingHoursPerDay,WorkingDaysPerWeek,Holidays,LaborCost
count,482.000000,482.000000,482.000000,482.000000,478.000000,476.000000,478.000000,482.000000,482.000000,476.000000,482.000000,482.000000,482.000000,478.000000,482.000000,482.000000,482.000000,4.820000e+02
mean,450.500000,5483.334025,100.448133,14.934295,32.909163,0.950231,34.382448,0.029855,4.552863,12.490357,2988.691535,12415.163299,30292.669295,3034.616925,7.495851,5.533195,12.728216,3.107624e+06
std,139.285678,2557.835299,24.267446,1.698398,16.271757,0.143847,14.929971,0.011845,0.028257,4.261515,1183.107803,4310.838939,11307.609772,1118.615664,1.106108,0.499415,4.056615,9.197860e+05
min,210.000000,1002.000000,41.000000,12.020000,5.750000,0.700000,8.280000,0.010000,4.550000,5.000000,1002.390000,5101.950000,10026.140000,1009.290000,6.000000,5.000000,6.000000,1.555000e+06
25%,330.250000,3301.000000,88.000000,13.472500,19.115000,0.830000,21.420000,0.020000,4.550000,8.782500,1969.392500,8967.055000,20331.112500,2094.412500,7.000000,5.000000,9.000000,2.316250e+06
50%,450.500000,5566.000000,108.000000,15.005000,32.365000,0.940000,34.430000,0.030000,4.550000,12.470000,2910.490000,12368.755000,30721.785000,3033.740000,7.000000,6.000000,13.000000,3.127500e+06
75%,570.750000,7671.250000,119.000000,16.310000,47.015000,1.080000,47.007500,0.040000,4.550000,16.047500,4128.770000,15959.152500,40057.767500,4012.770000,8.000000,6.000000,16.000000,3.860000e+06
max,691.000000,9996.000000,129.000000,18.000000,62.460000,1.200000,59.890000,0.050000,5.000000,19.930000,4966.970000,19964.340000,49877.980000,4998.180000,9.000000,6.000000,20.000000,4.765000e+06

In [18]:
# Load  dataset 
df = pd.read_csv('BADR Exel Sheet.csv')

#Convert Date Columns to DateTime:
df['StartDate'] = pd.to_datetime(df['StartDate'], errors='coerce')
df['EndDate'] = pd.to_datetime(df['EndDate'], errors='coerce')

# Check for missing values in the dataset
missing_values = df.isnull().sum()
print(missing_values)

ProjectID             0
ProjectName           0
ProjectType           0
ProjectSize           0
ProjectComplexity     0
StartDate             0
EndDate               0
NumWorkers            0
HourlyRate            0
OvertimeRate          4
ProductivityRate      6
MarketWageRate        4
InflationRate         0
MinWage               0
LaborDemand           0
FringeBenefits        6
IndirectCosts         0
EquipmentCost         0
MaterialCost          0
ContingencyCost       4
WeatherImpact         0
WorkingHoursPerDay    0
WorkingDaysPerWeek    0
Holidays              0
LaborCost             0
dtype: int64

C:\Users\USER\AppData\Local\Temp\ipykernel_7972\355147953.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['StartDate'] = pd.to_datetime(df['StartDate'], errors='coerce')
C:\Users\USER\AppData\Local\Temp\ipykernel_7972\355147953.py:6: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['EndDate'] = pd.to_datetime(df['EndDate'], errors='coerce')

2. Encode Categorical Variables

In [19]:
# Drop the 'ProjectID' and 'ProjectName' columns
df.drop(columns=['ProjectID', 'ProjectName'], inplace=True)

# Define columns with missing values
columns_with_missing_values = ['HourlyRate', 'OvertimeRate', 'ProductivityRate', 
                               'MarketWageRate', 'FringeBenefits', 'ContingencyCost']

# Create an imputer object with a mean filling strategy
imputer = SimpleImputer(strategy='mean')

# Apply the imputer to the columns with missing values
df[columns_with_missing_values] = imputer.fit_transform(df[columns_with_missing_values])

# Check to ensure there are no missing values left
print(df.isnull().sum())

ProjectType           0
ProjectSize           0
ProjectComplexity     0
StartDate             0
EndDate               0
NumWorkers            0
HourlyRate            0
OvertimeRate          0
ProductivityRate      0
MarketWageRate        0
InflationRate         0
MinWage               0
LaborDemand           0
FringeBenefits        0
IndirectCosts         0
EquipmentCost         0
MaterialCost          0
ContingencyCost       0
WeatherImpact         0
WorkingHoursPerDay    0
WorkingDaysPerWeek    0
Holidays              0
LaborCost             0
dtype: int64

In [20]:


# One-hot encode categorical variables 
categorical_columns = [ 'ProjectType', 'ProjectComplexity', 'LaborDemand','WeatherImpact']
df = pd.get_dummies(df, columns=categorical_columns, drop_first=True)

df.head()

,ProjectSize,StartDate,EndDate,NumWorkers,HourlyRate,OvertimeRate,ProductivityRate,MarketWageRate,InflationRate,MinWage,...,ContingencyCost,WorkingHoursPerDay,WorkingDaysPerWeek,Holidays,LaborCost,ProjectType_Industrial,ProjectType_Residential,ProjectComplexity_Moderate,ProjectComplexity_Simple,LaborDemand_Low
0,8270,2007-01-04,2007-10-02,48,12.50,59.70,1.070000,39.13,0.02,4.55,...,3832.29,7,5,6,1555000,True,False,False,True,False
1,7949,2007-01-06,2009-07-07,125,17.00,16.01,0.790000,23.82,0.03,4.55,...,2168.58,9,5,20,4765000,True,False,False,False,False
2,3734,2007-01-06,2008-12-11,114,16.06,17.04,0.950231,38.81,0.01,4.55,...,4862.53,7,6,15,3725000,False,True,False,False,False
3,8513,2007-03-14,2009-08-06,125,17.65,18.80,0.820000,43.53,0.03,4.55,...,4021.45,7,6,19,4580000,False,True,False,False,False
4,4843,2007-03-19,2008-06-13,83,13.69,7.46,1.120000,31.39,0.03,4.55,...,3083.34,7,6,10,2460000,False,True,True,False,False

3. Feature Engineering

In [21]:
# Create new feature: Project Duration
df['ProjectDuration'] = (df['EndDate'] - df['StartDate']).dt.days

print(df[['StartDate', 'EndDate', 'ProjectDuration']].head())

   StartDate    EndDate  ProjectDuration
0 2007-01-04 2007-10-02              271
1 2007-01-06 2009-07-07              913
2 2007-01-06 2008-12-11              705
3 2007-03-14 2009-08-06              876
4 2007-03-19 2008-06-13              452

4. Normalize/Scale Numerical Features:

In [22]:
from sklearn.preprocessing import StandardScaler

# List of numerical features to scale
numerical_features = ['ProjectSize', 'NumWorkers', 'HourlyRate', 'OvertimeRate', 'ProductivityRate',
                      'MarketWageRate', 'InflationRate', 'MinWage', 'FringeBenefits', 'IndirectCosts',
                      'EquipmentCost', 'MaterialCost', 'ContingencyCost', 'ProjectDuration']

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the numerical features
df[numerical_features] = scaler.fit_transform(df[numerical_features])

df[numerical_features].head()

,ProjectSize,NumWorkers,HourlyRate,OvertimeRate,ProductivityRate,MarketWageRate,InflationRate,MinWage,FringeBenefits,IndirectCosts,EquipmentCost,MaterialCost,ContingencyCost,ProjectDuration
0,1.090595,-2.163500,-1.434778,1.655069,0.838726,0.319650,-0.832820,-0.101429,-1.217447e+00,-1.486074,1.295171,0.332151,0.716817,-1.690426
1,0.964967,1.012771,1.217531,-1.043987,-1.122077,-0.711164,0.012273,-0.101429,-2.388293e-01,-0.697001,0.409307,-1.302504,-0.778251,1.802328
2,-0.684622,0.559018,0.663493,-0.980356,0.000000,0.298105,-1.677912,-0.101429,4.198971e-16,-1.105520,-1.495320,1.563646,1.642627,0.670719
3,1.185695,1.012771,1.600642,-0.871628,-0.911991,0.615900,0.012273,-0.101429,1.184185e+00,-1.095908,-0.359759,-1.151149,0.886803,1.601032
4,-0.250602,-0.719740,-0.733389,-1.572184,1.188870,-0.201480,0.012273,-0.101429,1.515118e+00,0.778758,-0.584496,0.223541,0.043784,-0.705709

In [23]:
df.head()

,ProjectSize,StartDate,EndDate,NumWorkers,HourlyRate,OvertimeRate,ProductivityRate,MarketWageRate,InflationRate,MinWage,...,WorkingHoursPerDay,WorkingDaysPerWeek,Holidays,LaborCost,ProjectType_Industrial,ProjectType_Residential,ProjectComplexity_Moderate,ProjectComplexity_Simple,LaborDemand_Low,ProjectDuration
0,1.090595,2007-01-04,2007-10-02,-2.163500,-1.434778,1.655069,0.838726,0.319650,-0.832820,-0.101429,...,7,5,6,1555000,True,False,False,True,False,-1.690426
1,0.964967,2007-01-06,2009-07-07,1.012771,1.217531,-1.043987,-1.122077,-0.711164,0.012273,-0.101429,...,9,5,20,4765000,True,False,False,False,False,1.802328
2,-0.684622,2007-01-06,2008-12-11,0.559018,0.663493,-0.980356,0.000000,0.298105,-1.677912,-0.101429,...,7,6,15,3725000,False,True,False,False,False,0.670719
3,1.185695,2007-03-14,2009-08-06,1.012771,1.600642,-0.871628,-0.911991,0.615900,0.012273,-0.101429,...,7,6,19,4580000,False,True,False,False,False,1.601032
4,-0.250602,2007-03-19,2008-06-13,-0.719740,-0.733389,-1.572184,1.188870,-0.201480,0.012273,-0.101429,...,7,6,10,2460000,False,True,True,False,False,-0.705709

In [24]:
print(df.columns)

Index(['ProjectSize', 'StartDate', 'EndDate', 'NumWorkers', 'HourlyRate',
       'OvertimeRate', 'ProductivityRate', 'MarketWageRate', 'InflationRate',
       'MinWage', 'FringeBenefits', 'IndirectCosts', 'EquipmentCost',
       'MaterialCost', 'ContingencyCost', 'WorkingHoursPerDay',
       'WorkingDaysPerWeek', 'Holidays', 'LaborCost', 'ProjectType_Industrial',
       'ProjectType_Residential', 'ProjectComplexity_Moderate',
       'ProjectComplexity_Simple', 'LaborDemand_Low', 'ProjectDuration'],
      dtype='object')

5. Normalize/Scale Numerical Features:

In [25]:
from sklearn.preprocessing import StandardScaler

# List of numerical features to scale
numerical_features = ['ProjectSize', 'NumWorkers', 'HourlyRate', 'OvertimeRate', 'ProductivityRate',
                      'MarketWageRate', 'InflationRate', 'MinWage', 'FringeBenefits', 'IndirectCosts',
                      'EquipmentCost', 'MaterialCost', 'ContingencyCost', 'WorkingHoursPerDay',
                      'WorkingDaysPerWeek', 'Holidays', 'ProjectDuration']

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the numerical features
df[numerical_features] = scaler.fit_transform(df[numerical_features])

# Display scaled numerical features to verify
df[numerical_features].head()

,ProjectSize,NumWorkers,HourlyRate,OvertimeRate,ProductivityRate,MarketWageRate,InflationRate,MinWage,FringeBenefits,IndirectCosts,EquipmentCost,MaterialCost,ContingencyCost,WorkingHoursPerDay,WorkingDaysPerWeek,Holidays,ProjectDuration
0,1.090595,-2.163500,-1.434778,1.655069,8.387260e-01,0.319650,-0.832820,-0.101429,-1.217447e+00,-1.486074,1.295171,0.332151,0.716817,-0.44875,-1.068748,-1.660302,-1.690426
1,0.964967,1.012771,1.217531,-1.043987,-1.122077e+00,-0.711164,0.012273,-0.101429,-2.388293e-01,-0.697001,0.409307,-1.302504,-0.778251,1.36127,-1.068748,1.794437,1.802328
2,-0.684622,0.559018,0.663493,-0.980356,1.105616e-17,0.298105,-1.677912,-0.101429,3.351332e-16,-1.105520,-1.495320,1.563646,1.642627,-0.44875,0.935674,0.560602,0.670719
3,1.185695,1.012771,1.600642,-0.871628,-9.119914e-01,0.615900,0.012273,-0.101429,1.184185e+00,-1.095908,-0.359759,-1.151149,0.886803,-0.44875,0.935674,1.547670,1.601032
4,-0.250602,-0.719740,-0.733389,-1.572184,1.188870e+00,-0.201480,0.012273,-0.101429,1.515118e+00,0.778758,-0.584496,0.223541,0.043784,-0.44875,0.935674,-0.673234,-0.705709

Columns Not to Scale
StartDate
EndDate
LaborCost (target variable)
ProjectType_Industrial
ProjectType_Residential
ProjectComplexity_Moderate
ProjectComplexity_Simple
LaborDemand_Low

In [26]:
# Save the preprocessed DataFrame to a CSV file
df.to_csv('preprocessed_labor_cost_data.csv', index=False)

print("Preprocessed data saved to 'preprocessed_labor_cost_data.csv'")

Preprocessed data saved to 'preprocessed_labor_cost_data.csv'